security:
    encoders:
        App\Entity\User:
            # We just want to use bcrypt, nothing else
            algorithm: bcrypt

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login

        api:
            pattern: ^/api
            stateless: true
            provider: user_provider
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
