version: '3'

services:
  api:
    build:
      context: ./api
    environment:
      APP_ENV: prod
      APP_SECRET: 7bd55ac5911b16c59ce265b025a2618d
      APP_PORT: 8001
      DB_HOST: db
      DATABASE_URL: postgresql://exo:rootme@db:5432/auth-db?serverVersion=12&charset=utf8
    ports:
      - "8001:8001"
  whoami:
    build:
      context: ./whoami
    ports:
      - "8000:80"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: exo
      POSTGRES_PASSWORD: rootme
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
