version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: exo
      POSTGRES_PASSWORD: rootme
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
  kv:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
