version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: exo
      POSTGRES_PASSWORD: rootme
  kv:
    image: redis:latest
    restart: always
